SELECT DISTINCT ?g ?obj ?technique
WHERE {
  GRAPH ?g {

     ?dig a crmdig:D1_Digital_Object . }
     ?dig  ecrm:P129_is_about ?img .

      ?dig ecrm:P129_is_about ?obj .
      ?obj a ecrm:E22_Man-Made_Object .
      ?dig ecrm:P129_is_about ?prd .
      ?obj  dc:identifier ?id .

OPTIONAL {
         { ?prd ecrm:P32_used_general_technique ?x
       { SELECT ?x SAMPLE(?lab) as ?technique
         WHERE { ?x skos:prefLabel ?lab . FILTER (lang(?lab) = "en")}
       } . FILTER(isIRI(?x)) }
       UNION
       { ?prd ecrm:P32_used_general_technique ?technique .
        FILTER (isIRI(?technique) = false)
        FILTER (lang(?technique) = "en")}
}


}